version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Indiana/Indianapolis
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/Indiana/Indianapolis
    open-pull-requests-limit: 3
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
