import { Analysis, ENGINE_VERSION } from "./compiler";
import { Project } from "./schema";

export interface TestSpec {
  version: "contrast-tests/1";
  project: Project;
  checks: {
    id: string;
    kind: "same" | "different";
    left: string;
    right: string;
    channel: string;
    observationIds: string[];
    executable: boolean;
    modelStatus: string;
  }[];
}
export function makeTestSpec(a: Analysis): TestSpec {
  return {
    version: "contrast-tests/1",
    project: a.project,
    checks: a.project.requirements.map((r) => {
      const channel = a.channels.find((c) => c.channel === r.channel)!;
      // Equivalence checks exercise ALL enabled releases, including rejected candidates.
      // Otherwise an empty selected set would make every privacy test pass vacuously.
      const ids =
        r.kind === "same"
          ? a.project.observations
              .filter((o) => o.enabled && o.channels.includes(r.channel))
              .map((o) => o.id)
          : channel.selected.length
            ? channel.selected
            : channel.candidates
                .filter((c) => c.status === "admissible")
                .map((c) => c.id);
      const executable =
        ids.length > 0 &&
        ids.every(
          (id) =>
            a.project.observations.find((o) => o.id === id)!.source ===
            "adapter",
        );
      return {
        id: r.id,
        kind: r.kind,
        left: r.left,
        right: r.right,
        channel: r.channel,
        observationIds: ids,
        executable,
        modelStatus: channel.contradictions.length
          ? "contradictory"
          : r.kind === "different"
            ? channel.covered.includes(r.id)
              ? "covered"
              : "uncovered"
            : channel.candidates.some(
                  (c) => ids.includes(c.id) && c.violations.length,
                )
              ? "violation"
              : "review candidate evidence",
      };
    }),
  };
}
const jsonLiteral = (value: unknown) =>
  JSON.stringify(value, null, 2)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
export function generateJest(spec: TestSpec): string {
  return `/** Generated by ${ENGINE_VERSION}. NOT EXECUTED by export.\n * Place in apps/web/src/lib/contrast/__tests__/exported.test.ts.\n * Run npm test --workspace=@nova/web -- --runInBand exported.test.ts\n * Adapter inputs are data. Assertions come from separately declared requirements.\n * Model-only checks are pending, not passing. Uncovered executable requirements fail. */\nimport { observe } from '../adapters';\nimport { normalize } from '../schema';\nimport type { TestSpec } from '../bundle';\nconst spec: TestSpec = ${jsonLiteral(spec)};\ndescribe('Exported Contrast requirements', () => {\n  for (const check of spec.checks) {\n    if (!check.executable) { test.todo(check.id + ': missing executable observation/adapter integration'); continue; }\n    test(check.id + ': ' + check.left + ' ' + check.kind + ' ' + check.right + ' on ' + check.channel, () => {\n      const vector = (caseId: string) => check.observationIds.map(id => {\n        const o = spec.project.observations.find(item => item.id === id)!;\n        const c = spec.project.cases.find(item => item.id === caseId)!;\n        const value = normalize(o, observe(o.adapter!, c.input ?? '', o.operation!));\n        expect(value).not.toBeNull();\n        return value;\n      });\n      const left = vector(check.left), right = vector(check.right);\n      if (check.kind === 'same') expect(left).toEqual(right);\n      else expect(left).not.toEqual(right);\n    });\n  }\n});\n`;
}
export function readableReport(a: Analysis): string {
  return [
    `# ${a.project.name}`,
    "",
    `Engine: ${a.engineVersion}. Schema: ${a.project.schemaVersion}.`,
    `Analysis mode: ${a.execution.mode}; ${a.execution.adapterCalls} built-in adapter observations executed. Exported tests: NOT EXECUTED.`,
    "",
    "Results apply only to supplied finite cases, exact categories, and explicit numeric bins. No tolerance relation, physical validation, universal correctness, or unseen-state guarantee.",
    "",
    ...a.channels.flatMap((c) => [
      `## ${a.project.channels.find((x) => x.id === c.channel)!.name}`,
      `Selection: ${c.selection}. Cost: ${c.cost}. Selected: ${c.selected.join(", ") || "(none)"}.`,
      "Exact means minimum cost for coverable declared distinctions using admissible enabled observations, not full coverage of impossible requirements. Costs are independent per channel; not a joint acquisition optimization.",
      ...c.contradictions.map(
        (x) =>
          `CONTRADICTION ${x.requirement.id}: ${x.requirement.left} / ${x.requirement.right}; equivalence chain: ${x.chain.join(" → ") || "same case"}.`,
      ),
      ...c.uncovered.map(
        (x) =>
          `UNCOVERED ${x.requirement.id}: ${x.requirement.left} / ${x.requirement.right}. ${x.reason}`,
      ),
      ...c.candidates
        .filter((x) => x.status !== "not-on-channel")
        .flatMap((x) => [
          `${x.id}: ${x.status}; separates [${x.separates.join(", ")}]; collisions [${x.collisions.join(", ")}]; incomplete [${x.incomplete.join(", ")}].`,
          ...x.violations.map(
            (v) =>
              `  Equivalence violation: ${v.left}=${JSON.stringify(v.leftValue)}, ${v.right}=${JSON.stringify(v.rightValue)}; chain ${v.chain.join(" → ")}.`,
          ),
          ...x.unknownEquivalences.map(
            (v) => `  Unverified equivalence: ${v.left} / ${v.right}.`,
          ),
        ]),
      ...c.collisions.map(
        (x) =>
          `DECODER COLLISION ${JSON.stringify(x.vector)}: ${x.caseIds.join(", ")}.`,
      ),
      `Incomplete decoder rows: ${c.incompleteCases.join(", ") || "none"}.`,
      "",
    ]),
    ...a.adapterErrors.map(
      (e) => `ADAPTER ERROR ${e.observation}/${e.caseId}: ${e.message}`,
    ),
  ].join("\n");
}
export function makeBundle(a: Analysis) {
  const spec = makeTestSpec(a);
  return {
    bundleVersion: "nova-contrast-bundle/1",
    project: a.project,
    analysis: a,
    provenance: {
      engineVersion: a.engineVersion,
      schemaVersion: a.project.schemaVersion,
      exportedAt: new Date().toISOString(),
      observations: a.project.observations.map((o) => ({
        id: o.id,
        source: o.source,
        adapter: o.adapter || null,
      })),
      execution: a.execution,
      scope:
        "Finite supplied model; adapters executed locally; exported tests not executed by export.",
    },
    decoders: a.channels.map((c) => ({ channel: c.channel, ...c.decoder })),
    unresolved: a.channels.map((c) => ({
      channel: c.channel,
      contradictions: c.contradictions,
      uncovered: c.uncovered,
      collisions: c.collisions,
      incompleteCases: c.incompleteCases,
    })),
    testSpecification: spec,
    files: {
      "requirements.test.ts": generateJest(spec),
      "decoder.cjs": decoderModule(a),
      "report.md": readableReport(a),
      "adapter-contract.md":
        "Adapter interface: observe(adapterId, caseInput, observationId) -> string | boolean | number | null. Implement integrations in trusted repository code. Do not execute uploaded code. Return null for unavailable measurements. Numeric observations require declared bins. Supply independent relation requirements; do not calculate expectations using the implementation being tested. Imported tables without a built-in adapter are model analysis only. No external system was tested.",
    },
  };
}

export function decoderModule(a: Analysis): string {
  const data = a.channels.map((c) => ({ channel: c.channel, ...c.decoder }));
  return `// Standalone lookup for supplied cases only. Inputs are normalized categorical/bin vectors.\nconst decoders = ${jsonLiteral(data)};\nfunction decode(channel, vector) {\n const decoder = decoders.find(d => d.channel === channel);\n if (!decoder || !Array.isArray(vector) || vector.length !== decoder.observationIds.length || vector.some(v => v === null || !['string', 'boolean'].includes(typeof v))) return { status: 'unknown', candidateCaseIds: [] };\n const compatible = decoder.rows.filter(row => row.values.every((v, i) => v === null || v === vector[i]));\n const complete = compatible.filter(row => !row.values.includes(null));\n return { status: !complete.length ? 'unknown' : compatible.length === 1 ? 'unique' : 'ambiguous', candidateCaseIds: compatible.map(row => row.caseId) };\n}\nmodule.exports = { decoders, decode };\n`;
}
