export declare const SERVICE_PORTS: {
    readonly GATEWAY: 3000;
    readonly AUTH: 3001;
    readonly ORCHESTRATOR: 3002;
    readonly EVENTBUS: 3003;
    readonly AUDIT: 3004;
    readonly NOTIFIER: 3005;
    readonly BILLING: 3006;
    readonly TRADEBOT: 3010;
    readonly STOREBOT: 3011;
    readonly SOCIALBOT: 3012;
    readonly RESEARCHBOT: 3013;
    readonly OPSBOT: 3014;
    readonly FORGEBOT: 3015;
    readonly MARKETDATA: 3020;
    readonly CONTENTDATA: 3021;
    readonly COMMERCEDATA: 3022;
};
export declare const EVENT_TYPES: {
    readonly SYSTEM_STARTUP: "system.startup";
    readonly SYSTEM_SHUTDOWN: "system.shutdown";
    readonly KILL_SWITCH_ENABLED: "system.killswitch.enabled";
    readonly KILL_SWITCH_DISABLED: "system.killswitch.disabled";
    readonly USER_CREATED: "auth.user.created";
    readonly USER_LOGIN: "auth.user.login";
    readonly USER_LOGOUT: "auth.user.logout";
    readonly POLICY_CREATED: "auth.policy.created";
    readonly POLICY_UPDATED: "auth.policy.updated";
    readonly GOAL_CREATED: "orchestrator.goal.created";
    readonly GOAL_UPDATED: "orchestrator.goal.updated";
    readonly GOAL_COMPLETED: "orchestrator.goal.completed";
    readonly TASK_CREATED: "orchestrator.task.created";
    readonly TASK_STARTED: "orchestrator.task.started";
    readonly TASK_COMPLETED: "orchestrator.task.completed";
    readonly TASK_FAILED: "orchestrator.task.failed";
    readonly APPROVAL_REQUESTED: "orchestrator.approval.requested";
    readonly APPROVAL_RESOLVED: "orchestrator.approval.resolved";
    readonly SCAN_EXECUTED: "trade.scan.executed";
    readonly SIGNAL_GENERATED: "trade.signal.generated";
    readonly BACKTEST_RUN: "trade.backtest.run";
    readonly PAPER_TRADE_OPENED: "trade.paper.opened";
    readonly PAPER_TRADE_CLOSED: "trade.paper.closed";
    readonly LIVE_TRADE_OPENED: "trade.live.opened";
    readonly LIVE_TRADE_CLOSED: "trade.live.closed";
    readonly PRODUCT_CREATED: "store.product.created";
    readonly PRODUCT_UPDATED: "store.product.updated";
    readonly LISTING_PUBLISHED: "store.listing.published";
    readonly ORDER_RECEIVED: "store.order.received";
    readonly ORDER_SHIPPED: "store.order.shipped";
    readonly CONTENT_CREATED: "social.content.created";
    readonly CONTENT_SCHEDULED: "social.content.scheduled";
    readonly CONTENT_POSTED: "social.content.posted";
    readonly METRICS_INGESTED: "social.metrics.ingested";
    readonly KB_DOC_CREATED: "research.kb.created";
    readonly PROPOSAL_CREATED: "research.proposal.created";
    readonly PROPOSAL_APPROVED: "research.proposal.approved";
    readonly PROPOSAL_REJECTED: "research.proposal.rejected";
    readonly PATCH_PROPOSED: "forge.patch.proposed";
    readonly PATCH_APPROVED: "forge.patch.approved";
    readonly PATCH_DEPLOYED: "forge.patch.deployed";
    readonly PATCH_ROLLED_BACK: "forge.patch.rolledback";
    readonly BOT_TASK_RECEIVED: "bot.task.received";
    readonly BOT_TASK_COMPLETED: "bot.task.completed";
    readonly BOT_ERROR: "bot.error";
};
export declare const RATE_LIMITS: {
    readonly API_REQUESTS_PER_MINUTE: 100;
    readonly AUTH_ATTEMPTS_PER_MINUTE: 10;
    readonly BOT_TASKS_PER_MINUTE: 30;
    readonly BOT_MAX_FAILURES_PER_HOUR: 50;
    readonly MARKET_DATA_REQUESTS_PER_MINUTE: 60;
    readonly SOCIAL_API_REQUESTS_PER_MINUTE: 30;
};
export declare const AUTOMATION_MODES: {
    readonly RECOMMEND: "recommend";
    readonly ASSIST: "assist";
    readonly AUTOMATE: "automate";
};
export declare const TRADING_DEFAULTS: {
    readonly MAX_POSITION_SIZE_PERCENT: 5;
    readonly MAX_LOSS_PER_TRADE_PERCENT: 2;
    readonly MAX_DAILY_LOSS_PERCENT: 6;
    readonly DEFAULT_STOP_LOSS_PERCENT: 5;
    readonly MIN_SCORE_FOR_SIGNAL: 70;
    readonly BACKTEST_DEFAULT_DAYS: 90;
};
export declare const CONTENT_DEFAULTS: {
    readonly SHORT_FORM_MAX_DURATION: 60;
    readonly LONG_FORM_MIN_DURATION: 300;
    readonly SCHEDULE_LOOKAHEAD_DAYS: 14;
    readonly MAX_POSTS_PER_DAY: 3;
};
export declare const DB_DEFAULTS: {
    readonly PAGE_SIZE: 20;
    readonly MAX_PAGE_SIZE: 100;
    readonly EVENT_RETENTION_DAYS: 365;
};
export declare const HTTP_STATUS: {
    readonly OK: 200;
    readonly CREATED: 201;
    readonly NO_CONTENT: 204;
    readonly BAD_REQUEST: 400;
    readonly UNAUTHORIZED: 401;
    readonly FORBIDDEN: 403;
    readonly NOT_FOUND: 404;
    readonly CONFLICT: 409;
    readonly UNPROCESSABLE_ENTITY: 422;
    readonly TOO_MANY_REQUESTS: 429;
    readonly INTERNAL_SERVER_ERROR: 500;
    readonly SERVICE_UNAVAILABLE: 503;
};
export declare const ERROR_CODES: {
    readonly INVALID_CREDENTIALS: "AUTH_001";
    readonly TOKEN_EXPIRED: "AUTH_002";
    readonly INSUFFICIENT_PERMISSIONS: "AUTH_003";
    readonly VALIDATION_FAILED: "VAL_001";
    readonly INVALID_INPUT: "VAL_002";
    readonly NOT_FOUND: "RES_001";
    readonly ALREADY_EXISTS: "RES_002";
    readonly RATE_LIMITED: "RATE_001";
    readonly AUTOMATION_DISABLED: "KILL_001";
    readonly BOT_EXECUTION_FAILED: "BOT_001";
    readonly BOT_APPROVAL_REQUIRED: "BOT_002";
    readonly EXTERNAL_API_ERROR: "EXT_001";
    readonly EXTERNAL_API_TIMEOUT: "EXT_002";
};
